backend:
  name: git-gateway
  branch: main # or master depending on your default branch name

media_folder: "assets/uploads"

collections:
  - name: "ticker"
    label: "News Ticker Headlines"
    files:
      - file: "ticker.json"
        label: "Ticker Headlines"
        name: "ticker_file"
        fields:
          - label: "Headlines"
            name: "headlines"
            widget: "list"
            field: { label: "Headline Text", name: "headline", widget: "string" }
